import { Creator, Product, Rankings } from '@/types';

export const creators: Creator[] = [
  {
    slug: 'studio-minimal',
    display_name: 'Studio Minimal',
    category: '生活雑貨',
    bio_short: '余白と機能を両立させたライフスタイルプロダクトを提案',
    bio_full: '「Less is More」をコンセプトに、日常に溶け込むミニマルなデザインプロダクトを展開。無駄を削ぎ落とし、本質的な機能美を追求しています。',
    active_since_year: 2021,
    lifetime_sales_jpy: 18500000,
    lifetime_units: 3200,
    projects_count: 4,
    avatar_seed: 'minimal-design-01',
  },
  {
    slug: 'tech-innovators',
    display_name: 'Tech Innovators',
    category: 'ガジェット',
    bio_short: '日常を効率化するスマートガジェットの開発',
    bio_full: 'テクノロジーと実用性を融合させ、毎日を少しだけ快適にするガジェットを設計。クラウドファンディングで4度の成功を収めています。',
    active_since_year: 2020,
    lifetime_sales_jpy: 32000000,
    lifetime_units: 5600,
    projects_count: 5,
    avatar_seed: 'tech-future-02',
  },
  {
    slug: 'fabric-atelier',
    display_name: 'Fabric Atelier',
    category: 'アパレル',
    bio_short: 'サステナブル素材で作る、長く愛せる服',
    bio_full: '環境負荷を抑えた素材選びと、時代に左右されないデザインで、10年後も着続けられる服を提案。',
    active_since_year: 2022,
    lifetime_sales_jpy: 12300000,
    lifetime_units: 1850,
    projects_count: 3,
    avatar_seed: 'fabric-nature-03',
  },
  {
    slug: 'beauty-lab',
    display_name: 'Beauty Lab',
    category: 'ビューティ',
    bio_short: '成分にこだわる、科学的スキンケアブランド',
    bio_full: '皮膚科学に基づいた成分配合で、肌本来の力を引き出すスキンケアを開発。シンプルで効果的な処方が支持されています。',
    active_since_year: 2021,
    lifetime_sales_jpy: 24700000,
    lifetime_units: 8900,
    projects_count: 6,
    avatar_seed: 'beauty-science-04',
  },
  {
    slug: 'craft-works',
    display_name: 'Craft Works',
    category: 'クラフト',
    bio_short: '伝統技法と現代デザインの融合',
    bio_full: '日本の職人技術を現代のライフスタイルに落とし込んだハンドメイドプロダクト。一つひとつ丁寧に作り上げています。',
    active_since_year: 2019,
    lifetime_sales_jpy: 15800000,
    lifetime_units: 980,
    projects_count: 7,
    avatar_seed: 'craft-tradition-05',
  },
  {
    slug: 'urban-essentials',
    display_name: 'Urban Essentials',
    category: '生活雑貨',
    bio_short: '都市生活に最適化した機能的な日用品',
    bio_full: '狭いスペースでも快適に暮らせる、コンパクトで多機能な生活雑貨を提案。実用性とデザイン性を両立しています。',
    active_since_year: 2020,
    lifetime_sales_jpy: 21500000,
    lifetime_units: 4300,
    projects_count: 5,
    avatar_seed: 'urban-modern-06',
  },
  {
    slug: 'smart-mobility',
    display_name: 'Smart Mobility',
    category: 'ガジェット',
    bio_short: '移動をもっと自由に、スマートに',
    bio_full: 'コンパクトな電動モビリティとアクセサリーで、都市での移動体験を再定義。環境にも優しい選択肢を提供します。',
    active_since_year: 2021,
    lifetime_sales_jpy: 45000000,
    lifetime_units: 2100,
    projects_count: 3,
    avatar_seed: 'mobility-future-07',
  },
  {
    slug: 'home-comfort',
    display_name: 'Home Comfort',
    category: '生活雑貨',
    bio_short: '心地よい暮らしを作る、こだわりのインテリア雑貨',
    bio_full: '五感で感じる心地よさを大切に、素材と形状にこだわったホームアイテムを展開。リラックスできる空間作りをサポートします。',
    active_since_year: 2022,
    lifetime_sales_jpy: 9800000,
    lifetime_units: 2400,
    projects_count: 2,
    avatar_seed: 'home-cozy-08',
  },
];

export const products: Product[] = [
  {
    slug: 'minimal-desk-organizer',
    product_name: 'ミニマルデスクオーガナイザー',
    category: '生活雑貨',
    campaign_status: 'indemand',
    funding_percent: 1240,
    lifetime_sales_jpy: 8500000,
    lifetime_units: 1800,
    creator_slug: 'studio-minimal',
    description: '必要最小限のスペースで、デスク周りを整理整頓。マグネット式で自由に組み替え可能。',
    why_successful: '在宅ワークの増加で「デスク環境を整えたい」というニーズが高まり、ミニマルなデザインと機能性が海外で高く評価されました。',
  },
  {
    slug: 'smart-charging-station',
    product_name: 'スマート充電ステーション',
    category: 'ガジェット',
    campaign_status: 'funded',
    funding_percent: 890,
    lifetime_sales_jpy: 15200000,
    lifetime_units: 2800,
    creator_slug: 'tech-innovators',
    description: '最大5台同時充電可能。ケーブルを隠してスッキリ収納できるデザイン。',
    why_successful: '複数デバイスを持つユーザーが増え、充電の煩雑さを解決する製品として支持されました。',
  },
  {
    slug: 'eco-tote-bag',
    product_name: 'エコトートバッグ',
    category: 'アパレル',
    campaign_status: 'live',
    funding_percent: 340,
    lifetime_sales_jpy: 4200000,
    lifetime_units: 1400,
    creator_slug: 'fabric-atelier',
    description: 'リサイクルコットン100%。軽量で耐久性があり、毎日使える一枚。',
  },
  {
    slug: 'peptide-serum',
    product_name: 'ペプチドセラム',
    category: 'ビューティ',
    campaign_status: 'indemand',
    funding_percent: 2100,
    lifetime_sales_jpy: 19800000,
    lifetime_units: 7200,
    creator_slug: 'beauty-lab',
    description: '高濃度ペプチド配合の美容液。シンプル処方で敏感肌にも優しい。',
    why_successful: '成分の透明性と科学的根拠を重視する海外市場で、クリーンビューティとして注目されました。',
  },
  {
    slug: 'ceramic-coffee-dripper',
    product_name: 'セラミックコーヒードリッパー',
    category: 'クラフト',
    campaign_status: 'funded',
    funding_percent: 650,
    lifetime_sales_jpy: 7300000,
    lifetime_units: 850,
    creator_slug: 'craft-works',
    description: '職人が一つずつ手作りする、美しい曲線のドリッパー。熱伝導率が安定し、毎回同じ味を再現。',
    why_successful: 'サードウェーブコーヒー文化の広がりと、日本の職人技術への関心が合致しました。',
  },
  {
    slug: 'folding-step-stool',
    product_name: '折りたたみステップスツール',
    category: '生活雑貨',
    campaign_status: 'indemand',
    funding_percent: 980,
    lifetime_sales_jpy: 11200000,
    lifetime_units: 3200,
    creator_slug: 'urban-essentials',
    description: '厚さ3cmまで折りたためる、軽量アルミ製スツール。耐荷重150kg。',
    why_successful: '省スペース性と高い耐久性が評価され、都市部の小さな住宅での需要が高まりました。',
  },
  {
    slug: 'electric-scooter',
    product_name: 'コンパクト電動スクーター',
    category: 'ガジェット',
    campaign_status: 'archived',
    lifetime_sales_jpy: 38000000,
    lifetime_units: 1800,
    creator_slug: 'smart-mobility',
    description: '折りたたみ可能な電動スクーター。最大30km走行可能で、通勤に最適。',
    why_successful: 'ラストワンマイル問題の解決手段として、環境意識の高い都市部で大ヒット。',
  },
  {
    slug: 'aromatherapy-diffuser',
    product_name: 'アロマディフューザー',
    category: '生活雑貨',
    campaign_status: 'live',
    funding_percent: 420,
    lifetime_sales_jpy: 5600000,
    lifetime_units: 1600,
    creator_slug: 'home-comfort',
    description: '静音設計で、寝室にも最適。木目調のデザインがインテリアに馴染む。',
  },
  {
    slug: 'wireless-earbuds-pro',
    product_name: 'ワイヤレスイヤホン Pro',
    category: 'ガジェット',
    campaign_status: 'funded',
    funding_percent: 1500,
    lifetime_sales_jpy: 16800000,
    lifetime_units: 2800,
    creator_slug: 'tech-innovators',
    description: 'ノイズキャンセリング搭載。最大40時間再生可能な長時間バッテリー。',
    why_successful: '音質と価格のバランスが評価され、大手ブランドの代替品として選ばれました。',
  },
  {
    slug: 'vitamin-c-essence',
    product_name: 'ビタミンCエッセンス',
    category: 'ビューティ',
    campaign_status: 'indemand',
    funding_percent: 1800,
    lifetime_sales_jpy: 4900000,
    lifetime_units: 1700,
    creator_slug: 'beauty-lab',
    description: '安定型ビタミンC20%配合。朝晩使える、刺激の少ない処方。',
  },
];

export const rankings: Rankings = {
  personal_lifetime: [
    { slug: 'smart-mobility', value: 45000000 },
    { slug: 'tech-innovators', value: 32000000 },
    { slug: 'beauty-lab', value: 24700000 },
    { slug: 'urban-essentials', value: 21500000 },
    { slug: 'studio-minimal', value: 18500000 },
    { slug: 'craft-works', value: 15800000 },
    { slug: 'fabric-atelier', value: 12300000 },
    { slug: 'home-comfort', value: 9800000 },
  ],
  best_single_product: [
    { slug: 'electric-scooter', value: 38000000 },
    { slug: 'peptide-serum', value: 19800000 },
    { slug: 'wireless-earbuds-pro', value: 16800000 },
    { slug: 'smart-charging-station', value: 15200000 },
    { slug: 'folding-step-stool', value: 11200000 },
    { slug: 'minimal-desk-organizer', value: 8500000 },
    { slug: 'ceramic-coffee-dripper', value: 7300000 },
    { slug: 'aromatherapy-diffuser', value: 5600000 },
  ],
  product_lifetime: [
    { slug: 'electric-scooter', value: 38000000 },
    { slug: 'peptide-serum', value: 19800000 },
    { slug: 'wireless-earbuds-pro', value: 16800000 },
    { slug: 'smart-charging-station', value: 15200000 },
    { slug: 'folding-step-stool', value: 11200000 },
    { slug: 'minimal-desk-organizer', value: 8500000 },
    { slug: 'ceramic-coffee-dripper', value: 7300000 },
    { slug: 'aromatherapy-diffuser', value: 5600000 },
  ],
};

export function getCreatorBySlug(slug: string): Creator | undefined {
  return creators.find((c) => c.slug === slug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCreator(creatorSlug: string): Product[] {
  return products.filter((p) => p.creator_slug === creatorSlug);
}
